.TH TRIBE-CLI "1" "June 2016" "tribe-cli 0.12"
.SH NAME
tribe-cli \- a remote procedure call client for Tribe Core. 
.SH SYNOPSIS
tribe-cli [options] <command> [params] \- Send command to Tribe Core. 
.TP
tribe-cli [options] help \- Asks Tribe Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the tribe-cli program. tribe-cli is an RPC client used to send commands to Tribe Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBtribed\fP, \fBtribe.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
